TARGET=snakes

LIB=/mnt/c/Prj/Altera/C/moxiebox/modules/lib
INCLUDE=/mnt/c/Prj/Altera/C/moxiebox/modules/include

FILES = $(TARGET) $(LIB)/sprintf $(LIB)/string $(LIB)/stdio  $(LIB)/floatimpl

ASM_LIST := $(foreach file,$(FILES), $(file).s) $(LIB)/consts.s

all: compile assemble copy

compile:
	@for file in $(FILES); do \
    moxiebox-gcc -I$(INCLUDE) -S $${file}.c -o $${file}.s -fverbose-asm; \
	done
	
assemble:
	java -jar ../FPGA_Assembler.jar -s -b=197632 $(ASM_LIST)

copy:
	cp $(TARGET).bin ../
