TARGET=mxbx_mirage

LIB=/mnt/c/Prj/Altera/C/moxiebox/modules/lib

FILES = $(TARGET) $(LIB)/mouse $(LIB)/sprintf $(LIB)/string $(LIB)/stdio $(LIB)/graphics $(LIB)/floatimpl

ASM_LIST := $(foreach file,$(FILES), $(file).s) $(LIB)/keyboard.s $(LIB)/files.s $(LIB)/graphics320.s $(LIB)/graphics640.s $(LIB)/fonts.s $(LIB)/consts.s

all: compile assemble copy

compile:
	@for file in $(FILES); do \
    moxiebox-gcc -fsigned-char -S $${file}.c -o $${file}.s -fverbose-asm; \
	done
	
assemble:
	java -jar ../FPGA_Assembler.jar -s -b=197632 $(ASM_LIST)

copy:
	cp $(TARGET).bin ../mirage.bin
	